# Generated by Django 4.1.5 on 2023-01-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film_director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.TextField(help_text="Enter the film's director", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_genre', models.CharField(help_text='Enter the genre', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text="Enter the film's name", max_length=32)),
                ('film_year', models.DateField(blank=True, null=True)),
                ('synopsis', models.TextField(help_text="Enter the film's summary", max_length=256)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.film_director')),
                ('genre', models.ManyToManyField(to='cine.genre')),
            ],
        ),
    ]
