# Generated by Django 4.1.5 on 2023-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
