# Generated by Django 4.1.5 on 2023-01-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_film_director_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_director',
            name='films',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.movie'),
        ),
    ]
