# Generated by Django 4.1.5 on 2023-01-29 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_film_director_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_director',
            name='director_name',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(help_text="Enter the film's summary", max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text="Enter the film's name", max_length=16),
        ),
        migrations.CreateModel(
            name='WhereSeeMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro', primary_key=True, serialize=False)),
                ('place', models.CharField(blank=True, choices=[('c', 'Cine'), ('t', 'Tv'), ('v', 'VOD')], default='c', help_text='Donde ver la película', max_length=1)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.movie')),
            ],
        ),
    ]
